- include_vars: base.yml

- name: determine base name
  set_fact:
    base_name: '{{ base.name }}'

- block:
  - name: 'create base {{ base_name }}'
    shell: |
      pot create-base \
      {% if base.name|length %} -b {{ base.name }}{% endif %} \ 
      {% if base.release|length %} -r {{ base.release }}{% endif %} \ 
  when:
  - base.state == 'present'
  - not base.name in potintel.bases

- block:
  - name: 'destroy base {{ base_name }}'
    shell: 'pot destroy -br {{ base.name}}'
  when:
  - base.state == 'absent'
  - 'base-{{ base.name }} in potintel.jails'
