- include_vars: fscomp.yml

- name: determine fscomp name
  set_fact:
    fscomp_name: '{{ fscomp.name }}'

- block:
  - name: 'create fs comp {{ fscomp_name }}'
    shell: |
      pot create-fscomp \
      {% if fscomp.name|length %} -f {{ fscomp.name }}{% endif %} \ 
  when:
  - fscomp.state == 'present'
  - not fscomp.name in potintel.fscomps

- block:
  - name: 'destroy fs comp {{ fscomp_name }}'
    shell: 'pot destroy -f {{ fscomp.name }}'
  when:
  - fscomp.state == 'absent'
  - fscomp.name in potintel.fscomps
