- include_vars: jail.yml

- name: determine jail name
  set_fact:
    jail_name: '{{ jail.name }}'

- block:
  - name: 'destroy jail {{ jail_name }} '
    shell: 'pot stop {{ jail.name }} || pot destroy -rp {{ jail.name }}'
  - name: 'Update pot facts'
    setup:
      filter: ansible_local
  when:
  - jail.state == 'absent'
  - potintel.jails[jail.name] is defined

- block:
  - name: 'create jail {{ jail_name }}'
    shell: |
      pot create \
      {% if jail.name|length %} -p {{ jail.name }}{% endif %} \ 
      {% if jail.ip|length %} -i {{ jail.ip }}{% endif %} \ 
      {% if jail.dns|length %} -d {{ jail.dns }}{% endif %} \ 
      {% if jail.base|length %} -b {{ jail.base }}{% endif %} \ 
      {% if jail.type|length %} -t {{ jail.type }}{% endif %} \ 
      {% if jail.flavour|length %} -f {{ jail.flavour }}{% endif %} \ 
      {% if jail.pot|length %} -P {{ jail.pot }}{% endif %} \ 
      {% if jail.level|length %} -l {{ jail.level }}{% endif %} \ 
      {% if jail.network_type|length %} -N {{ jail.network_type }}{% endif %} \ 
      {% if jail.network_stack|length %} -S {{ jail.network_stack }}{% endif %} \ 
      {% if jail.bridge_name|length %} -B {{ jail.bridge_name }}{% endif %} \ 
  - name: 'update pot facts'
    setup:
      filter: ansible_local
  when:
  - jail.state != 'absent'
  - not jail.name in potintel.jails

- block:
  - name: 'stop jail {{ jail_name }}'
    shell: 'pot stop {{ jail.name }}'
  - set_fact:
      potintel.jails[jail.name].active = false
  when:
  - potintel.jails[jail.name] is defined
  - potintel.jails[jail.name].active|bool
  - jail.state in ['stopped', 'restarted', 'present']

- block:
  - name: 'rename jail {{ jail_name }}'
    shell: 'pot rename -p {{ jail.name }} -n {{ jail.new_name }}'
  - setup:
      filter: ansible_local
  when:
  - potintel.jails[jail.name] is defined
  - jail.state not in ['started', 'absent']
  - jail.new_name|length

- block:
  - name: 'start jail {{ jail_name }}'
    shell: 'pot start {{ jail.name }}'
  - set_fact:
      potintel.jails[jail.name].active = true
  when:
  - potintel.jails[jail.name] is defined
  - jail.state in ['started', 'restarted']
