- file:
    path: '/usr/local/etc/ansible/facts.d'
    state: directory
  become: yes
- copy:
    dest: '/usr/local/etc/ansible/facts.d/pot.fact'
    src: 'pot_local.fact'
    mode: '0755'
  become: yes

- name: Installing Pot
  community.general.pkgng:
    name: pot
    state: present

- name: Gathering Facts
  setup:
    filter: ansible_local

- block:
  - name: enable pot service
    community.general.sysrc:
      name: pot_enable
      value: YES
  - name: create pot config
    template:
      src: pot.conf.j2
      dest: /usr/local/etc/pot/pot.conf
      mode: 0644
  - name: initialize pot
    shell: pot init
  - name: Gathering Facts
    setup:
      filter: ansible_local
  when:
  - pot.enabled|bool
  - not potintel.initialized|bool

- block:
  - name: de-initialize pot
    shell: pot de-init
  - name: disable pot service
    community.general.sysrc:
      name: pot_enable
      state: absent
  - name: Gathering Facts
    setup:
      filter: ansible_local
  when:
  - not pot.enabled|bool
  - potintel.initialized|bool

- block:
  - name: initialize vnet
    file:
      path: '/usr/local/etc/ansible/.pot_vnet_init'
      state: touch
  - shell: pot vnet-start
  - name: Gathering Facts
    setup:
      filter: ansible_local
  when:
  - pot.enabled|bool
  - pot.vnet_enabled|bool
  - not potintel.vnet_initialized|bool

- name: Install ansible-managed Flavour
  copy:
    dest: '/usr/local/etc/pot/flavours/ansible-managed.sh'
    src: 'ansible-managed.sh'
    mode: '0755'
  become: yes
